### ISSUE TITLE
"fcntl" lib is not available in Windows

### ISSUE THREAD

**Issue by duongnamphuong** [TilCreator/Tapas-Comic-Downloader#11]
I play Python 3.7.4 on Windows. I get this error when trying to run **python tapas-dl.py "https://tapas.io/series/Erma"**
ModuleNotFoundError: No module named 'fcntl'
I tried using pip to install it, but it is not available
The same problem occured with "termios" lib when I commented out the **import fcntl** code before running the python file again.
Did I have a mistake?

**Comment by duongnamphuong** [comment]
According to what I looked up, these libraries are UNIX exclusive, or at least unavailable on Windows. If it is that case, I guess you don't have to fix this.

**Comment by TilCreator** [comment]
Should be fixed now.
Now it will just fall back to terminal size 80x200.

**Comment by SKevo18** [comment]
I'm still getting the `fcntl` not found message. I have successfully installed all the required modules, except for this single one. Running Windows 10.

**Edit:** When I just modified the script to not care about fcntl at all it seems to work perfectly. Perhaps you should make a Windows-only version(?)

Bah, humbug, imma do it.

**Comment by TilCreator** [comment]
Can you give me the exact error?

**Comment by SKevo18** [comment]
> Can you give me the exact error?

Sure:
![image](https://user-images.githubusercontent.com/39010496/73270459-0116b800-41df-11ea-9056-7528206497c7.png)

If you wonder why I renamed the script, it's just to not conflict with my modified script that works, but it's actually the script I have found on this GitHub (aka. the most recent and original one).

**Comment by TilCreator** [comment]
Ups, my bad, used `except` the wrong way:
https://github.com/TilCreator/Tapas-Comic-Downloader/blob/d1fbfb9497d044aff9a0f2f6269b224813baa523/tapas-dl.py#L21
https://docs.python.org/3/tutorial/errors.html#handling-exceptions

**Comment by TilCreator** [comment]
Will push a fix in a few minutes/hours

**Comment by TilCreator** [comment]
Should be fixed now, could you pls try it?

**Comment by duongnamphuong** [comment]
Thank you very much. It is working.
![Erma](https://user-images.githubusercontent.com/12604672/73319137-d54b0f00-427e-11ea-9a36-3e9d1f1da0dc.png)
I'll tell the final result later, when they are all downloaded.

**Comment by duongnamphuong** [comment]
The console suddenly stopped showing this message:

Downloaded image 1/1 from page 38/414 (47/628 images)...
Downloaded image 1/1 from page 39/414 (48/628 images)...
Traceback (most recent call last):
  File "tapas-dl.py", line 135, in <module>
    pageData['id'], img[img.rindex('.') + 1:])), 'wb') as f:
OSError: [Errno 22] Invalid argument: 'Erma [Erma]\\048 - 40 - 0 - Erma- May I Have This Dance? - #261918.jpg'

![Erma](https://user-images.githubusercontent.com/12604672/73319622-4a6b1400-4280-11ea-99c4-6f0d58c4f938.png)

But this seems irrelevant to this current issue. It can be closed, I guess.

**Comment by SKevo18** [comment]
> The console suddenly stopped showing this message:
> 
> Downloaded image 1/1 from page 38/414 (47/628 images)...
> Downloaded image 1/1 from page 39/414 (48/628 images)...
> Traceback (most recent call last):
> File "tapas-dl.py", line 135, in
> pageData['id'], img[img.rindex('.') + 1:])), 'wb') as f:
> OSError: [Errno 22] Invalid argument: 'Erma [Erma]\048 - 40 - 0 - Erma- May I Have This Dance? - #261918.jpg'

Just by the absolute way, I get this issue after some images too, I have absolutely no idea what causes that.

**Comment by TilCreator** [comment]
Probably #6
or rather Windows doesn't support Unicode and even some non-special characters very well and I didn't implement a fix for this jet.
