### ISSUE TITLE
EMPTY DOWNLOAD

### ISSUE THREAD

**Issue by bap269** [TilCreator/Tapas-Comic-Downloader#31]
I successfully downloaded a series on TAPAS but it was empty?
How to fix it?

**Comment by TilCreator** [comment]
Please be a bit more specific, what was the command you used, what did it output and so on?

**Comment by bap269** [comment]
here's a screen shot of my cmd
![xuanlong](https://user-images.githubusercontent.com/54578953/99217124-48c00c00-2812-11eb-8b57-9b025f05f0b8.PNG)

**Comment by TilCreator** [comment]
"Downloading pages" means that it is crawling for the image data, you won't see any images in the directory until it says "Downloading images"

**Comment by bap269** [comment]
Ohh thanks...
So do I wait for "downloading image" to appear or???

**Comment by TilCreator** [comment]
Jup

**Comment by bap269** [comment]
it just stays on this part tho....
![xuanlong](https://user-images.githubusercontent.com/54578953/99248521-8db06680-2843-11eb-94a1-d846d4a6b1d6.PNG)

**Comment by TilCreator** [comment]
That is weird, I will try to replicate it.

**Comment by TilCreator** [comment]
On my machine: It does create the epub, but all the text is missing, will check what is going wrong

**Comment by TilCreator** [comment]
Shoud be fixed in 2373a2e

**Comment by TilCreator** [comment]
Also sadly about half of the book is for logged in users only and the script doesn't know how to handle that jet

**Comment by TilCreator** [comment]
(You will also find the epub next to the directory, not in the directory)

**Comment by Trashblob** [comment]
> Also sadly about half of the book is for logged in users only and the script doesn't know how to handle that jet

Is there a known workaround to do that? Maybe loading out of a cached website or something?

**Comment by TilCreator** [comment]
The easiest way would be to export the session cookies from the browser and then get the script to use those cookies (the used module is called requests and should support using cookies for requests). That should give a small time window where the script can fake being a logged in user. The other option would be to use the browser itself (with a logged in user) for making the requests with selenium or similar, example: https://gitlab.com/TilCreator/mc-vanilla-pp/-/blob/master/helpers/crawl_curseforge.py#L14

Sadly I will not be able to implement that in the next weeks. But for everyone who knows what their doing this should be enough to implement this themselves.

**Comment by Trashblob** [comment]
Damn that was a fast response, thank you! 
I'll check that out, even tho I have no Idea what I'm doing (yet) lol. 

But good to hear that you're still working on it, because I really like your work. Keep it up. :)

**Comment by TilCreator** [comment]
9b3904135c47f70efc746cde198eaae01ec578bd should fix this/(where this has developed to)

**Comment by t4rra** [comment]
Am getting the same issue when downloading novels, the text is still missing. Tried again with a cookie file, got `AttributeError: 'MozillaCookieJar' object has no attribute 'update'` in return.

**Comment by archziac** [comment]
> Shoud be fixed in [2373a2e](https://github.com/TilCreator/Tapas-Comic-Downloader/commit/2373a2e1782a02180d45f4440fc221befbbf6794)

Hello. I want to say that I'm still facing this problem. I have downloaded a novel but whenever i open the EPUB file it's just the chapter names and the table of contents in there and except that all the chapters are empty
